name: "Upload SARIF"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted #ubuntu --- con PVS-Studio installato
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Compile
      run: |
        touch makefile
        echo "file.o: f.c" > makefile
        echo -e "\tgcc -Wall -lm f.c" >> makefile
        pvs-studio-analyzer trace -- make -j8
        pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
        plog-converter PVS-Studio.log -t sarif -o results.sarif
   
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artefatti
        path: results.sarif
      
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
